language: python
python: "2.7"
services:
  - docker

sudo: required

branches:
  only:
    - master
    - dev

script:
  - docker run --rm -w /workspace -v $(pwd):/workspace inhumantsar/ansible:centos7 /start.sh -v -e 'private_repo_apt_repos=[]'
  - docker run --rm -w /workspace -v $(pwd):/workspace inhumantsar/ansible:xenial /start.sh -v -e 'private_repo_rpm_repos=[]'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
