- hosts: localhost
  connection: local
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
    - 'vars/test-xenial.yml'
  tasks:
    - name: Test Xenial
      include_tasks: 'tasks/main.yml'
