- hosts: localhost
  connection: local
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
    - 'vars/test.yml'
  tasks:
    - name: Install python-apt
      package: name=python-apt
    - name: Test CentOS 7, PyPI, and Docker
      include_tasks: 'tasks/main.yml'
