---
# tasks file for private-repos
- debug: msg="Starting tasks from private-repos..."

- name: Set up RPM repos...
  yum_repository:
    name: "{{private_repo_name_prefix}}-{{item}}"
    description: "{{private_repo_desc_prefix}} - {{item}}"
    baseurl: "https://{{private_repo_username}}:{{private_repo_encrypted_password}}@{{private_repo_url_base}}/{{private_repo_url_pathprefix}}{{item}}"
    gpgcheck: "{{ private_repo_rpm_gpgcheck }}"
  with_items:
    - "{{private_repo_rpm_repos}}"
  become: True
  when: ansible_os_family == "RedHat"

- name: Install RPM signing key
  shell: "rpm --import https://{{private_repo_username}}:{{private_repo_encrypted_password}}@{{private_repo_url_base}}/{{private_repo_url_pathprefix}}/api/gpg/key/public"
  become: True
  when: ansible_os_family == "RedHat"
    

- name: Set up APT repos...
  apt_repository:
    filename: "{{private_repo_name_prefix}}-{{item['name']}}"
    repo: "deb https://{{private_repo_username}}:{{private_repo_encrypted_password}}@{{private_repo_url_base}}/{{private_repo_url_pathprefix}}/{{item['name']}} {{item['codename']}} {{item['component']}}"
    update_cache: no
  with_items:
    - "{{private_repo_apt_repos}}"
  become: True
  when: ansible_os_family == "Debian"

- name: Set up PyPI repos...
  template:
    src: templates/pip.conf.j2
    dest: "/etc/pip.conf"
    owner: root
    group: root
    mode: 0644
  become: True

- name: Log in to Docker repos...
  command: "docker login -p '{{private_repo_password}}' -u '{{private_repo_username}}' {{item}}.{{private_repo_url_base}}"
  with_items:
    - "{{private_repo_docker_repos}}"
